# Importacion de librerias

In [1]:
import pandas as pd
import numpy as np

#Librerias para graficar
import matplotlib.pyplot as plt
import seaborn as sns

#Libreria para importar CSV
import os

#Libreria para conectarte a la API de REE
import requests

import json
from pandas import json_normalize
from flatten_json import flatten_json

#Librerias para trabajar con fechas
import datetime as dt
from datetime import datetime, date, time, timedelta, timezone
import pytz
import calendar
from dateutil import rrule
from calendar import isleap #Determina si un año es bisiesto

# Lista de variables

In [2]:
demanda = []
# Codigo de cada comunidad autonoma
geo_ids = ['4','5','6','7','8','9','10','11','8744','8745','13','14','15','16','17','8743','8742','20','21']
start_date =[]
end_date = []
month_days = []
#dates_demanda = []
#values_demanda = []

In [3]:
andalucia_demanda =[]
andalucia_date = []
aragon_demanda =[]
aragon_date = []
cantabria_demanda =[]
cantabria_date = []
castilla_la_mancha_demanda =[]
castilla_la_mancha_date = []
castilla_leon_demanda =[]
castilla_leon_date = []
cataluna_demanda =[]
cataluna_date = []
pais_vasco_demanda =[]
pais_vasco_date = []
asturias_demanda=[]
asturias_date=[]
ceuta_demanda=[]
ceuta_date = []
melilla_demanda=[]
melilla_date=[]
madrid_demanda=[]
madrid_date=[]
navarra_demanda=[]
navarra_date=[]
valencia_demanda=[]
valencia_date=[]
extremadura_demanda=[]
extremadura_date=[]
galicia_demanda=[]
galicia_date=[]
islas_baleares_demanda=[]
islas_baleares_date=[]
islas_canarias_demanda=[]
islas_canarias_date=[]
la_rioja_demanda=[]
la_rioja_date=[]
murcia_demanda=[]
murcia_date=[]

# Periodo para el cual se van a obtener los datos

En este paso es importante saber que el maximo periodo que se puede obtener en una request en la API de REE son 2 años. Por tal motivo es que se hace un bucle For que vaya de a 2 años y recorra todo el periodo que necesitamos.
El maximo periodo historico de información que se puede descargar es Enero-2011

In [4]:
formato_fecha = "%Y-%m-%dT%H:%M"
today = datetime.today()
today_year = today.year
today_month = today.month
start_today_month = datetime (today_year,today_month,1)
start_period = datetime(2011, 1, 1, 0, 0)
end_period =(start_today_month - timedelta(seconds=60))

In [5]:
for date in rrule.rrule(rrule.MONTHLY, dtstart=start_period, until=end_period): 
    if date.month in [4,6,9,11]:
        days = 30
    elif date.month == 2:
        if isleap(date.year):
            days = 29
        else:
            days = 28
    else:
        days = 31
    month_days.append(days)

In [6]:
for i in range (start_period.year,end_period.year + 1,2):
    start_dates = datetime(i, 1, 1, 0, 0)
    start_date.append(start_dates.strftime(formato_fecha))
    if start_dates.year + 1 < end_period.year:
        end_dates = datetime(start_dates.year + 1,12,31,23,59).strftime(formato_fecha)
    else:
        end_dates = datetime(end_period.year,end_period.month,calendar.monthrange (end_period.year,end_period.month)[1],23,59).strftime(formato_fecha)
    end_date.append(end_dates)

# Conexión a la API de REE

In [7]:
def REE_url_demanda_comunidad (lang,category,widget,start_date,end_date,time_trunc,geo_trunc,geo_limit,geo_ids):
    for x in geo_ids:
        for i,j in zip(start_date,end_date):
            API_REE =f'https://apidatos.ree.es/{lang}/datos/{category}/{widget}?start_date={i}&end_date={j}&time_trunc={time_trunc}&geo_trunc={geo_trunc}&geo_limit={geo_limit}&geo_ids={x}'
        
            data_demanda=requests.get(API_REE)
            data_json_demanda = data_demanda.json()
            included_list_demanda = data_json_demanda['included']
            included_dict_demanda = included_list_demanda[0]
            attributes_dict_demanda = included_dict_demanda['attributes']
            values_list_demanda= attributes_dict_demanda['values']
            demanda.append(values_list_demanda)

In [8]:
REE_url_demanda_comunidad ('es','demanda','evolucion',start_date,end_date,'month','electric_system','ccaa',geo_ids)

In [9]:
for i in range(len(demanda)):
    if i < len(start_date):
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            andalucia_demanda.append(value_demanda)
            andalucia_date.append(date_demanda)
    elif len(start_date) <= i and i < len(start_date)*2:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            aragon_demanda.append(value_demanda)
            aragon_date.append(date_demanda) 
    elif len(start_date)*2 <= i and i < len(start_date)*3:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            cantabria_demanda.append(value_demanda)
            cantabria_date.append(date_demanda) 
    elif len(start_date)*3 <= i and i < len(start_date)*4:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            castilla_la_mancha_demanda.append(value_demanda)
            castilla_la_mancha_date.append(date_demanda)       
    elif len(start_date)*4 <= i and i < len(start_date)*5:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            castilla_leon_demanda.append(value_demanda)
            castilla_leon_date.append(date_demanda)
    elif len(start_date)*5 <= i and i < len(start_date)*6:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            cataluna_demanda.append(value_demanda)
            cataluna_date.append(date_demanda)  
    elif len(start_date)*6 <= i and i < len(start_date)*7:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            pais_vasco_demanda.append(value_demanda)
            pais_vasco_date.append(date_demanda) 
    elif len(start_date)*7 <= i and i < len(start_date)*8:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            asturias_demanda.append(value_demanda)
            asturias_date.append(date_demanda) 
    elif len(start_date)*8 <= i and i < len(start_date)*9:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            ceuta_demanda.append(value_demanda)
            ceuta_date.append(date_demanda) 
    elif len(start_date)*9 <= i and i < len(start_date)*10:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            melilla_demanda.append(value_demanda)
            melilla_date.append(date_demanda) 
    elif len(start_date)*10 <= i and i < len(start_date)*11:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            madrid_demanda.append(value_demanda)
            madrid_date.append(date_demanda) 
    elif len(start_date)*11 <= i and i < len(start_date)*12:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            navarra_demanda.append(value_demanda)
            navarra_date.append(date_demanda) 
    elif len(start_date)*12 <= i and i < len(start_date)*13:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            valencia_demanda.append(value_demanda)
            valencia_date.append(date_demanda)       
    elif len(start_date)*13 <= i and i < len(start_date)*14:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            extremadura_demanda.append(value_demanda)
            extremadura_date.append(date_demanda)
    elif len(start_date)*14 <= i and i < len(start_date)*15:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            galicia_demanda.append(value_demanda)
            galicia_date.append(date_demanda)  
    elif len(start_date)*15 <= i and i < len(start_date)*16:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            islas_baleares_demanda.append(value_demanda)
            islas_baleares_date.append(date_demanda) 
    elif len(start_date)*16 <= i and i < len(start_date)*17:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            islas_canarias_demanda.append(value_demanda)
            islas_canarias_date.append(date_demanda) 
    elif len(start_date)*17 <= i and i < len(start_date)*18:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            la_rioja_demanda.append(value_demanda)
            la_rioja_date.append(date_demanda) 
    elif len(start_date)*18 <= i and i < len(start_date)*19:
        a = demanda[i]
        for x in a:
            value_demanda = x['value']
            date_demanda = x['datetime']
            murcia_demanda.append(value_demanda)
            murcia_date.append(date_demanda)

# Verificacion

In [10]:
print(len(andalucia_demanda))
print(len(aragon_demanda))
print(len(cantabria_demanda))
print(len(castilla_la_mancha_demanda))
print(len(castilla_leon_demanda))
print(len(cataluna_demanda))
print(len(pais_vasco_demanda))
print(len(asturias_demanda))
print(len(ceuta_demanda))
print(len(melilla_demanda))
print(len(madrid_demanda))
print(len(navarra_demanda))
print(len(valencia_demanda))
print(len(extremadura_demanda))
print(len(galicia_demanda))
print(len(islas_baleares_demanda))
print(len(islas_canarias_demanda))
print(len(la_rioja_demanda))
print(len(murcia_demanda))

137
137
137
137
137
137
137
137
140
140
137
137
137
137
137
140
140
137
137

# Armado de Dataframe

In [11]:
demanda_comunidades_peninsula= pd.DataFrame({"dtime":andalucia_date,
                              "Andalucia":andalucia_demanda,
                              "Aragon":aragon_demanda,
                              "Cantabria":cantabria_demanda,
                              "Castilla-La Mancha":castilla_la_mancha_demanda,
                              "Castilla - Leon":castilla_leon_demanda,
                              "Cataluna":cataluna_demanda,
                              "Pais Vasco":pais_vasco_demanda,
                              "Asturias":asturias_demanda,
                              "Madrid":madrid_demanda,
                              "Navarra":navarra_demanda,
                              "Valencia":valencia_demanda,
                              "Extremadura":extremadura_demanda,
                              "Galicia":galicia_demanda,
                              "La Rioja":la_rioja_demanda,
                              "Murcia":murcia_demanda,
                               })
demanda_comunidades_out_peninsula = pd.DataFrame({"dtime":ceuta_date,
                                  "Ceuta":ceuta_demanda,
                                  "Melilla":melilla_demanda,
                                  "Islas Baleares":islas_baleares_demanda,
                                  "Islas Canarias":islas_canarias_demanda
                                   })

In [12]:
demanda_comunidades_peninsula['dtime']=pd.to_datetime(demanda_comunidades_peninsula['dtime'],utc = True,errors='coerce')
demanda_comunidades_peninsula['dtime']= demanda_comunidades_peninsula['dtime'].apply(lambda x : x.astimezone(pytz.timezone('Europe/Madrid')))
demanda_comunidades_peninsula['date']=demanda_comunidades_peninsula['dtime'].dt.date

In [13]:
demanda_comunidades_peninsula=demanda_comunidades_peninsula.drop('dtime',axis=1)
demanda_comunidades_peninsula.set_index('date',inplace=True)

In [15]:
demanda_comunidades_out_peninsula['dtime']=pd.to_datetime(demanda_comunidades_out_peninsula['dtime'],utc = True,errors='coerce')
demanda_comunidades_out_peninsula['dtime']= demanda_comunidades_out_peninsula['dtime'].apply(lambda x : x.astimezone(pytz.timezone('Europe/Madrid')))
demanda_comunidades_out_peninsula['date']=demanda_comunidades_out_peninsula['dtime'].dt.date

In [16]:
demanda_comunidades_out_peninsula=demanda_comunidades_out_peninsula.drop('dtime',axis=1)
demanda_comunidades_out_peninsula.set_index('date',inplace=True)

In [17]:
demanda_comunidades_peninsula.head()

,Andalucia,Aragon,Cantabria,Castilla-La Mancha,Castilla - Leon,Cataluna,Pais Vasco,Asturias,Madrid,Navarra,Valencia,Extremadura,Galicia,La Rioja,Murcia
date,,,,,,,,,,,,,,,
2011-01-01,3611370.158,956500.295,394458.733,1151079.404,1308023.490,4342582.019,1653043.915,1020147.744,2989140.888,442761.810,2526982.724,462009.524,1856313.192,163772.454,731156.254
2011-02-01,3206557.695,872527.978,366574.242,1039329.384,1189416.356,3908142.365,1590309.120,920399.066,2693270.528,419328.551,2271565.119,407235.603,1674718.220,151471.485,652478.722
2011-03-01,3363760.649,942539.985,402782.196,1092285.257,1264476.681,4218751.172,1742782.999,986152.384,2819434.247,453441.807,2373753.059,437535.389,1789358.239,162837.730,685604.110
2011-04-01,2902823.703,825725.543,361935.178,895004.912,1039440.167,3592544.226,1442490.251,881845.117,2245193.190,378083.837,1961970.722,353799.702,1583513.902,130206.861,592383.924
2011-05-01,2988726.944,874732.192,379054.143,942660.376,1106830.540,3886563.827,1545963.183,910096.249,2372782.482,415006.737,2095019.601,368543.527,1613757.255,141856.367,627598.985

In [18]:
demanda_comunidades_out_peninsula.tail()

                Ceuta    Melilla  Islas Baleares  Islas Canarias
date
2022-04-01  15441.195  14619.040      435906.977      672232.674
2022-05-01  16203.751  15612.354      471908.158      700461.265
2022-06-01  16614.684  16241.420      574251.053      692393.461
2022-07-01  17855.742  19131.127      701562.361      752730.424
2022-08-01  16827.505  20549.941      727484.518      754749.781